"""Initial database schema

Revision ID: 653b628c91ce
Revises: 
Create Date: 2025-10-30 15:45:52.407332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '653b628c91ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('employees', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('headquarters', sa.String(length=255), nullable=True),
    sa.Column('cik', sa.String(length=20), nullable=True),
    sa.Column('cusip', sa.String(length=9), nullable=True),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_delisted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    op.create_index(op.f('ix_companies_cik'), 'companies', ['cik'], unique=False)
    op.create_index(op.f('ix_companies_cusip'), 'companies', ['cusip'], unique=False)
    op.create_index(op.f('ix_companies_exchange'), 'companies', ['exchange'], unique=False)
    op.create_index(op.f('ix_companies_industry'), 'companies', ['industry'], unique=False)
    op.create_index(op.f('ix_companies_isin'), 'companies', ['isin'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_sector'), 'companies', ['sector'], unique=False)
    op.create_index(op.f('ix_companies_symbol'), 'companies', ['symbol'], unique=True)
    op.create_table('data_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('api_key_required', sa.Boolean(), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=True),
    sa.Column('rate_limit_per_day', sa.Integer(), nullable=True),
    sa.Column('provides_market_data', sa.Boolean(), nullable=False),
    sa.Column('provides_fundamental_data', sa.Boolean(), nullable=False),
    sa.Column('provides_news_data', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_sources'))
    )
    op.create_index(op.f('ix_data_sources_name'), 'data_sources', ['name'], unique=True)
    op.create_table('data_updates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('data_source', sa.String(length=100), nullable=False),
    sa.Column('symbols', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_updates'))
    )
    op.create_index(op.f('ix_data_updates_celery_task_id'), 'data_updates', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_data_updates_data_source'), 'data_updates', ['data_source'], unique=False)
    op.create_index(op.f('ix_data_updates_job_type'), 'data_updates', ['job_type'], unique=False)
    op.create_index(op.f('ix_data_updates_status'), 'data_updates', ['status'], unique=False)
    op.create_table('external_api_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('data_source', sa.String(length=100), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('request_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=False),
    sa.Column('response_size_bytes', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('is_rate_limited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_api_logs'))
    )
    op.create_index(op.f('ix_external_api_logs_data_source'), 'external_api_logs', ['data_source'], unique=False)
    op.create_index(op.f('ix_external_api_logs_status_code'), 'external_api_logs', ['status_code'], unique=False)
    op.create_table('screening_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('screen_name', sa.String(length=255), nullable=False),
    sa.Column('screen_type', sa.String(length=50), nullable=False),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_companies_screened', sa.Integer(), nullable=False),
    sa.Column('companies_passed', sa.Integer(), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_screening_results'))
    )
    op.create_index(op.f('ix_screening_results_screen_name'), 'screening_results', ['screen_name'], unique=False)
    op.create_index(op.f('ix_screening_results_screen_type'), 'screening_results', ['screen_type'], unique=False)
    op.create_index(op.f('ix_screening_results_session_id'), 'screening_results', ['session_id'], unique=False)
    op.create_index(op.f('ix_screening_results_user_id'), 'screening_results', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('refresh_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions'))
    )
    op.create_index(op.f('ix_user_sessions_refresh_token_hash'), 'user_sessions', ['refresh_token_hash'], unique=False)
    op.create_index(op.f('ix_user_sessions_token_hash'), 'user_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('subscription_tier', sa.String(length=50), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('request_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('audit_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('compliance_category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_compliance_category'), 'audit_logs', ['compliance_category'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_ip_address'), 'audit_logs', ['ip_address'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_session_id'), 'audit_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_success'), 'audit_logs', ['success'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('financial_ratios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=True),
    sa.Column('calculation_date', sa.Date(), nullable=False),
    sa.Column('current_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('quick_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('cash_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('operating_cash_flow_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('gross_profit_margin', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('operating_margin', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('net_profit_margin', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('roa', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('roe', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('roic', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('debt_to_equity', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('debt_to_assets', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('equity_multiplier', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('interest_coverage_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('asset_turnover', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('inventory_turnover', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('receivables_turnover', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('days_sales_outstanding', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('pe_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('pb_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('ps_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('ev_ebitda', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('peg_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('revenue_growth', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('earnings_growth', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('eps_growth', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('book_value_growth', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('piotroski_score', sa.Integer(), nullable=True),
    sa.Column('altman_z_score', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('beneish_m_score', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_financial_ratios_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_ratios')),
    sa.UniqueConstraint('company_id', 'period_type', 'fiscal_year', 'fiscal_quarter', name='uq_financial_ratio_period')
    )
    op.create_index(op.f('ix_financial_ratios_calculation_date'), 'financial_ratios', ['calculation_date'], unique=False)
    op.create_index(op.f('ix_financial_ratios_company_id'), 'financial_ratios', ['company_id'], unique=False)
    op.create_index(op.f('ix_financial_ratios_fiscal_quarter'), 'financial_ratios', ['fiscal_quarter'], unique=False)
    op.create_index(op.f('ix_financial_ratios_fiscal_year'), 'financial_ratios', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_financial_ratios_period_type'), 'financial_ratios', ['period_type'], unique=False)
    op.create_table('financial_statements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('statement_type', sa.String(length=20), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('data_source', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_financial_statements_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_statements')),
    sa.UniqueConstraint('company_id', 'statement_type', 'period_type', 'fiscal_year', 'fiscal_quarter', name='uq_financial_statement_period')
    )
    op.create_index(op.f('ix_financial_statements_company_id'), 'financial_statements', ['company_id'], unique=False)
    op.create_index(op.f('ix_financial_statements_fiscal_quarter'), 'financial_statements', ['fiscal_quarter'], unique=False)
    op.create_index(op.f('ix_financial_statements_fiscal_year'), 'financial_statements', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_financial_statements_period_type'), 'financial_statements', ['period_type'], unique=False)
    op.create_index(op.f('ix_financial_statements_report_date'), 'financial_statements', ['report_date'], unique=False)
    op.create_index(op.f('ix_financial_statements_statement_type'), 'financial_statements', ['statement_type'], unique=False)
    op.create_table('market_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('high_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('low_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('close_price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('adjusted_close', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('dividend_amount', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('split_coefficient', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_market_data_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_data')),
    sa.UniqueConstraint('company_id', 'price_date', name='uq_market_data_date')
    )
    op.create_index(op.f('ix_market_data_company_id'), 'market_data', ['company_id'], unique=False)
    op.create_index(op.f('ix_market_data_price_date'), 'market_data', ['price_date'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('total_cost_basis', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('day_change', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('day_change_percent', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('total_return', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_return_percent', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_portfolios_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolios'))
    )
    op.create_index(op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=False)
    op.create_table('watchlists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_watchlists_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watchlists'))
    )
    op.create_index(op.f('ix_watchlists_user_id'), 'watchlists', ['user_id'], unique=False)
    op.create_table('portfolio_holdings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('shares', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('average_cost', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('first_purchase_date', sa.Date(), nullable=False),
    sa.Column('last_purchase_date', sa.Date(), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('market_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('unrealized_gain_loss', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('unrealized_gain_loss_percent', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_portfolio_holdings_company_id_companies')),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_portfolio_holdings_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_holdings')),
    sa.UniqueConstraint('portfolio_id', 'company_id', name='uq_portfolio_holding')
    )
    op.create_index(op.f('ix_portfolio_holdings_company_id'), 'portfolio_holdings', ['company_id'], unique=False)
    op.create_index(op.f('ix_portfolio_holdings_portfolio_id'), 'portfolio_holdings', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_portfolio_holdings_symbol'), 'portfolio_holdings', ['symbol'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('shares', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('commission', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fees', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('taxes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('broker', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_transactions_company_id_companies')),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_transactions_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    op.create_index(op.f('ix_transactions_company_id'), 'transactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_transactions_external_id'), 'transactions', ['external_id'], unique=False)
    op.create_index(op.f('ix_transactions_portfolio_id'), 'transactions', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_transactions_symbol'), 'transactions', ['symbol'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_type'), 'transactions', ['transaction_type'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('watchlist_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('target_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('alert_price_above', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('alert_price_below', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_watchlist_items_company_id_companies')),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], name=op.f('fk_watchlist_items_watchlist_id_watchlists'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watchlist_items')),
    sa.UniqueConstraint('watchlist_id', 'company_id', name='uq_watchlist_item')
    )
    op.create_index(op.f('ix_watchlist_items_company_id'), 'watchlist_items', ['company_id'], unique=False)
    op.create_index(op.f('ix_watchlist_items_watchlist_id'), 'watchlist_items', ['watchlist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_items_watchlist_id'), table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_company_id'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_transactions_transaction_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_symbol'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_portfolio_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_external_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_company_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_portfolio_holdings_symbol'), table_name='portfolio_holdings')
    op.drop_index(op.f('ix_portfolio_holdings_portfolio_id'), table_name='portfolio_holdings')
    op.drop_index(op.f('ix_portfolio_holdings_company_id'), table_name='portfolio_holdings')
    op.drop_table('portfolio_holdings')
    op.drop_index(op.f('ix_watchlists_user_id'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_market_data_price_date'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_company_id'), table_name='market_data')
    op.drop_table('market_data')
    op.drop_index(op.f('ix_financial_statements_statement_type'), table_name='financial_statements')
    op.drop_index(op.f('ix_financial_statements_report_date'), table_name='financial_statements')
    op.drop_index(op.f('ix_financial_statements_period_type'), table_name='financial_statements')
    op.drop_index(op.f('ix_financial_statements_fiscal_year'), table_name='financial_statements')
    op.drop_index(op.f('ix_financial_statements_fiscal_quarter'), table_name='financial_statements')
    op.drop_index(op.f('ix_financial_statements_company_id'), table_name='financial_statements')
    op.drop_table('financial_statements')
    op.drop_index(op.f('ix_financial_ratios_period_type'), table_name='financial_ratios')
    op.drop_index(op.f('ix_financial_ratios_fiscal_year'), table_name='financial_ratios')
    op.drop_index(op.f('ix_financial_ratios_fiscal_quarter'), table_name='financial_ratios')
    op.drop_index(op.f('ix_financial_ratios_company_id'), table_name='financial_ratios')
    op.drop_index(op.f('ix_financial_ratios_calculation_date'), table_name='financial_ratios')
    op.drop_table('financial_ratios')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_success'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_session_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_ip_address'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_compliance_category'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_token_hash'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_refresh_token_hash'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_screening_results_user_id'), table_name='screening_results')
    op.drop_index(op.f('ix_screening_results_session_id'), table_name='screening_results')
    op.drop_index(op.f('ix_screening_results_screen_type'), table_name='screening_results')
    op.drop_index(op.f('ix_screening_results_screen_name'), table_name='screening_results')
    op.drop_table('screening_results')
    op.drop_index(op.f('ix_external_api_logs_status_code'), table_name='external_api_logs')
    op.drop_index(op.f('ix_external_api_logs_data_source'), table_name='external_api_logs')
    op.drop_table('external_api_logs')
    op.drop_index(op.f('ix_data_updates_status'), table_name='data_updates')
    op.drop_index(op.f('ix_data_updates_job_type'), table_name='data_updates')
    op.drop_index(op.f('ix_data_updates_data_source'), table_name='data_updates')
    op.drop_index(op.f('ix_data_updates_celery_task_id'), table_name='data_updates')
    op.drop_table('data_updates')
    op.drop_index(op.f('ix_data_sources_name'), table_name='data_sources')
    op.drop_table('data_sources')
    op.drop_index(op.f('ix_companies_symbol'), table_name='companies')
    op.drop_index(op.f('ix_companies_sector'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_isin'), table_name='companies')
    op.drop_index(op.f('ix_companies_industry'), table_name='companies')
    op.drop_index(op.f('ix_companies_exchange'), table_name='companies')
    op.drop_index(op.f('ix_companies_cusip'), table_name='companies')
    op.drop_index(op.f('ix_companies_cik'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
