"""Add foreign key constraints

Revision ID: 7bece66ce402
Revises: 653b628c91ce
Create Date: 2025-10-30 15:51:27.863574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bece66ce402'
down_revision: Union[str, Sequence[str], None] = '653b628c91ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_user_sessions_user_id_users'), 'user_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_sessions_user_id_users'), 'user_sessions', type_='foreignkey')
    # ### end Alembic commands ###
