"""
Default subscription plans for the platform.
"""
from decimal import Decimal

DEFAULT_PLANS = [
    {
        "name": "Free",
        "stripe_price_id": None,
        "price_monthly": Decimal("0.00"),
        "description": "Basic access for individual investors",
        "features": [
            "5 portfolio holdings",
            "Basic financial ratios",
            "Daily market data",
            "Basic watchlists",
        ],
        "limits": {
            "api_calls_per_day": 100,
            "portfolios": 1,
            "holdings_per_portfolio": 5,
            "watchlists": 1,
            "symbols_per_watchlist": 10,
            "backtests_per_month": 5,
            "exports_per_month": 3,
            "sentiment_requests_per_day": 10,
        },
        "sort_order": 0,
    },
    {
        "name": "Basic",
        "stripe_price_id": None,
        "price_monthly": Decimal("19.99"),
        "price_annually": Decimal("199.99"),
        "description": "Enhanced tools for active investors",
        "features": [
            "50 portfolio holdings",
            "Technical analysis (50+ indicators)",
            "Weekly sentiment analysis",
            "Email alerts",
            "5 portfolios",
        ],
        "limits": {
            "api_calls_per_day": 1000,
            "portfolios": 5,
            "holdings_per_portfolio": 50,
            "watchlists": 5,
            "symbols_per_watchlist": 50,
            "backtests_per_month": 50,
            "exports_per_month": 20,
            "sentiment_requests_per_day": 100,
        },
        "sort_order": 1,
    },
    {
        "name": "Pro",
        "stripe_price_id": None,
        "price_monthly": Decimal("49.99"),
        "price_annually": Decimal("499.99"),
        "description": "Professional tools for serious traders",
        "features": [
            "500 portfolio holdings",
            "Real-time data streaming",
            "Advanced analytics (Monte Carlo, VaR)",
            "Portfolio optimization",
            "Priority support",
            "25 portfolios",
        ],
        "limits": {
            "api_calls_per_day": 10000,
            "portfolios": 25,
            "holdings_per_portfolio": 500,
            "watchlists": 25,
            "symbols_per_watchlist": 200,
            "backtests_per_month": 500,
            "exports_per_month": 100,
            "sentiment_requests_per_day": 500,
        },
        "sort_order": 2,
    },
    {
        "name": "Enterprise",
        "stripe_price_id": None,
        "price_monthly": Decimal("199.99"),
        "price_annually": Decimal("1999.99"),
        "description": "Full platform access for teams and institutions",
        "features": [
            "Everything in Pro",
            "Unlimited portfolios and holdings",
            "Team accounts",
            "Custom reports",
            "API access",
            "Dedicated support",
            "Backtesting framework",
        ],
        "limits": {
            "api_calls_per_day": -1,
            "portfolios": -1,
            "holdings_per_portfolio": -1,
            "watchlists": -1,
            "symbols_per_watchlist": -1,
            "backtests_per_month": -1,
            "exports_per_month": -1,
            "sentiment_requests_per_day": -1,
        },
        "sort_order": 3,
    },
]
